openapi: 3.0.0
info:
  title: Задания
  version: 1.0.0
servers:
  - url: http://localhost:8080/api/
    description: Dev server
paths:
  /user:
    post:
      summary: Метод создания пользователя
      tags:
        - User
      requestBody:
        required: true
        content:  
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        '200':
          description: Успешный ответ, данные добавленного пользователя
          content:
            applicataion/json:
              schema:
                $ref: "#/components/schemas/User"
        'default':
          description: Ошибка
          content:
            applicataion/json:
              schema:
                $ref: "#/components/schemas/Error"
  /user/{user_id}/history:
    get:
      summary: Метод получения истории выполненных заданий пользователя
      tags:
        - User
      parameters:
        - name: user_id
          in: path
          required: true
          description: Идентификатор пользователя
          schema:
            type: integer
      responses:
        '200':
          description: Успешный ответ, история пользователя
          content:
            applicataion/json:
              schema:
                $ref: "#/components/schemas/UserHistory"
        'default':
          description: Ошибка
          content:
            applicataion/json:
              schema:
                $ref: "#/components/schemas/Error"        
  /quest:
    post:
      summary: Метод создания задания
      tags:
        - Quest
      requestBody:
        required: true
        content:  
          application/json:
            schema:
              $ref: "#/components/schemas/Quest"
      responses:
        '200':
          description: Успешный ответ, данные добавленного задания
          content:
            applicataion/json:
              schema:
                $ref: "#/components/schemas/Quest"
        'default':
          description: Ошибка
          content:
            applicataion/json:
              schema:
                $ref: "#/components/schemas/Error"
  /signal:
    post:
      summary: Метод сигнала сервису
      description: Выполняется транзакция, добавляющяя выполненное задание пользователю и пополняющая его баланс
      tags:
        - Signal
      requestBody:
        required: true
        content:  
          application/json:
            schema:
              $ref: "#/components/schemas/Signal"
      responses:
        '200':
          description: Успешный ответ, обновленные данные пользователя
          content:
            applicataion/json:
              schema:
                $ref: "#/components/schemas/User"
        'default':
          description: Ошибка
          content:
            applicataion/json:
              schema:
                $ref: "#/components/schemas/Error"               
components:
  schemas:
    User:
      type: object
      required: 
        - name
        - balance
      properties:
        user_id:
          type: integer
          example: 1
        name:
          type: string
          example: Danila
        balance:
          type: integer
          example: 0
    Quest:
      type: object
      required: 
        - name
        - cost
      properties:
        quest_id:
          type: integer
          example: 1
        name:
          type: string
          example: Create new task
        cost:
          type: integer
          example: 1000
    Signal:
      type: object
      required: 
        - user_id
        - quest_id
      properties:
        user_id:
          type: integer
          example: 20
        quest_id:
          type: integer
          example: 1
    UserHistory:
      type: object
      required: 
        - user_id
        - quests
      properties:
        user_id:
          type: integer
          example: 20
        quests:
          type: array
          items:
            $ref: "#/components/schemas/Quest"
          description: Список выполненных заданий  
    Error:
      type: object
      required: 
        - code
        - message
      properties:
        code:
          type: integer
        message:
          type: string